// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzgrqqakdazqrdgwvhqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Z3JxcWFrZGF6cXJkZ3d2aHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjY5MzIsImV4cCI6MjA3MDQwMjkzMn0.zeTl6S2_15UzUWMPVwIUe3kHOFD0OLrrTUza07mHAy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});